-- ============================================
-- Library Management System
-- Auto Generated Seed Data
-- Generated by BookSeedGenerator
-- ============================================
INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Clean Code',
    'Robert C. Martin',
    '9781000000001',
    'PROGRAMMING',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Clean Architecture',
    'Robert C. Martin',
    '9781000000002',
    'PROGRAMMING',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Clean Coder',
    'Robert C. Martin',
    '9781000000003',
    'PROGRAMMING',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Effective Java',
    'Joshua Bloch',
    '9781000000004',
    'PROGRAMMING',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Java Concurrency in Practice',
    'Brian Goetz',
    '9781000000005',
    'PROGRAMMING',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Head First Java',
    'Kathy Sierra',
    '9781000000006',
    'PROGRAMMING',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Spring in Action',
    'Craig Walls',
    '9781000000007',
    'PROGRAMMING',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Spring Boot in Action',
    'Craig Walls',
    '9781000000008',
    'PROGRAMMING',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Hibernate in Action',
    'Gavin King',
    '9781000000009',
    'PROGRAMMING',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Design Patterns',
    'Erich Gamma',
    '9781000000010',
    'PROGRAMMING',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Refactoring',
    'Martin Fowler',
    '9781000000011',
    'PROGRAMMING',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Domain-Driven Design',
    'Eric Evans',
    '9781000000012',
    'PROGRAMMING',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Pragmatic Programmer',
    'Andrew Hunt',
    '9781000000013',
    'PROGRAMMING',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Code Complete',
    'Steve McConnell',
    '9781000000014',
    'PROGRAMMING',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Working Effectively with Legacy Code',
    'Michael Feathers',
    '9781000000015',
    'PROGRAMMING',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Programming Pearls',
    'Jon Bentley',
    '9781000000016',
    'PROGRAMMING',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Introduction to Algorithms',
    'Thomas H. Cormen',
    '9781000000017',
    'PROGRAMMING',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Grokking Algorithms',
    'Aditya Bhargava',
    '9781000000018',
    'PROGRAMMING',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Computer Networks',
    'Andrew S. Tanenbaum',
    '9781000000019',
    'PROGRAMMING',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Operating System Concepts',
    'Abraham Silberschatz',
    '9781000000020',
    'PROGRAMMING',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'A Brief History of Time',
    'Stephen Hawking',
    '9781000000021',
    'SCIENCE',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Cosmos',
    'Carl Sagan',
    '9781000000022',
    'SCIENCE',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Astrophysics for People in a Hurry',
    'Neil deGrasse Tyson',
    '9781000000023',
    'SCIENCE',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Selfish Gene',
    'Richard Dawkins',
    '9781000000024',
    'SCIENCE',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Gene',
    'Siddhartha Mukherjee',
    '9781000000025',
    'SCIENCE',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Elegant Universe',
    'Brian Greene',
    '9781000000026',
    'SCIENCE',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Immortal Life of Henrietta Lacks',
    'Rebecca Skloot',
    '9781000000027',
    'SCIENCE',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Silent Spring',
    'Rachel Carson',
    '9781000000028',
    'SCIENCE',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Origin of Species',
    'Charles Darwin',
    '9781000000029',
    'SCIENCE',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Demon-Haunted World',
    'Carl Sagan',
    '9781000000030',
    'SCIENCE',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Six Easy Pieces',
    'Richard P. Feynman',
    '9781000000031',
    'SCIENCE',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'What If?',
    'Randall Munroe',
    '9781000000032',
    'SCIENCE',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Body: A Guide for Occupants',
    'Bill Bryson',
    '9781000000033',
    'SCIENCE',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Emperor of All Maladies',
    'Siddhartha Mukherjee',
    '9781000000034',
    'SCIENCE',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Brief Answers to the Big Questions',
    'Stephen Hawking',
    '9781000000035',
    'SCIENCE',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Sapiens',
    'Yuval Noah Harari',
    '9781000000036',
    'HISTORY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Homo Deus',
    'Yuval Noah Harari',
    '9781000000037',
    'HISTORY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Guns Germs and Steel',
    'Jared Diamond',
    '9781000000038',
    'HISTORY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Silk Roads',
    'Peter Frankopan',
    '9781000000039',
    'HISTORY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'India After Gandhi',
    'Ramachandra Guha',
    '9781000000040',
    'HISTORY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Discovery of India',
    'Jawaharlal Nehru',
    '9781000000041',
    'HISTORY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Lessons of History',
    'Will Durant',
    '9781000000042',
    'HISTORY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Wright Brothers',
    'David McCullough',
    '9781000000043',
    'HISTORY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Diary of a Young Girl',
    'Anne Frank',
    '9781000000044',
    'HISTORY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Rise and Fall of the Third Reich',
    'William L. Shirer',
    '9781000000045',
    'HISTORY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'SPQR',
    'Mary Beard',
    '9781000000046',
    'HISTORY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Team of Rivals',
    'Doris Kearns Goodwin',
    '9781000000047',
    'HISTORY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Second World War',
    'Antony Beevor',
    '9781000000048',
    'HISTORY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    '1776',
    'David McCullough',
    '9781000000049',
    'HISTORY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The History of the Ancient World',
    'Susan Wise Bauer',
    '9781000000050',
    'HISTORY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    '1984',
    'George Orwell',
    '9781000000051',
    'FICTION',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Animal Farm',
    'George Orwell',
    '9781000000052',
    'FICTION',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Hobbit',
    'J.R.R. Tolkien',
    '9781000000053',
    'FICTION',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Lord of the Rings',
    'J.R.R. Tolkien',
    '9781000000054',
    'FICTION',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Harry Potter and the Philosopher''s Stone',
    'J.K. Rowling',
    '9781000000055',
    'FICTION',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Harry Potter and the Chamber of Secrets',
    'J.K. Rowling',
    '9781000000056',
    'FICTION',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'To Kill a Mockingbird',
    'Harper Lee',
    '9781000000057',
    'FICTION',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Pride and Prejudice',
    'Jane Austen',
    '9781000000058',
    'FICTION',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Great Gatsby',
    'F. Scott Fitzgerald',
    '9781000000059',
    'FICTION',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Catcher in the Rye',
    'J.D. Salinger',
    '9781000000060',
    'FICTION',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Kite Runner',
    'Khaled Hosseini',
    '9781000000061',
    'FICTION',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Book Thief',
    'Markus Zusak',
    '9781000000062',
    'FICTION',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Life of Pi',
    'Yann Martel',
    '9781000000063',
    'FICTION',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Chronicles of Narnia',
    'C.S. Lewis',
    '9781000000064',
    'FICTION',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Da Vinci Code',
    'Dan Brown',
    '9781000000065',
    'FICTION',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Gone Girl',
    'Gillian Flynn',
    '9781000000066',
    'FICTION',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Shining',
    'Stephen King',
    '9781000000067',
    'FICTION',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Dune',
    'Frank Herbert',
    '9781000000068',
    'FICTION',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Fahrenheit 451',
    'Ray Bradbury',
    '9781000000069',
    'FICTION',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Alchemist',
    'Paulo Coelho',
    '9781000000070',
    'FICTION',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Steve Jobs',
    'Walter Isaacson',
    '9781000000071',
    'BIOGRAPHY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Elon Musk',
    'Walter Isaacson',
    '9781000000072',
    'BIOGRAPHY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Einstein: His Life and Universe',
    'Walter Isaacson',
    '9781000000073',
    'BIOGRAPHY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Leonardo da Vinci',
    'Walter Isaacson',
    '9781000000074',
    'BIOGRAPHY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Long Walk to Freedom',
    'Nelson Mandela',
    '9781000000075',
    'BIOGRAPHY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Wings of Fire',
    'A.P.J. Abdul Kalam',
    '9781000000076',
    'BIOGRAPHY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Playing It My Way',
    'Sachin Tendulkar',
    '9781000000077',
    'BIOGRAPHY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Becoming',
    'Michelle Obama',
    '9781000000078',
    'BIOGRAPHY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Shoe Dog',
    'Phil Knight',
    '9781000000079',
    'BIOGRAPHY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'My Experiments with Truth',
    'Mahatma Gandhi',
    '9781000000080',
    'BIOGRAPHY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Autobiography of Malcolm X',
    'Malcolm X',
    '9781000000081',
    'BIOGRAPHY',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Alexander Hamilton',
    'Ron Chernow',
    '9781000000082',
    'BIOGRAPHY',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Benjamin Franklin',
    'Walter Isaacson',
    '9781000000083',
    'BIOGRAPHY',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Churchill: Walking with Destiny',
    'Andrew Roberts',
    '9781000000084',
    'BIOGRAPHY',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Open',
    'Andre Agassi',
    '9781000000085',
    'BIOGRAPHY',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Atomic Habits',
    'James Clear',
    '9781000000086',
    'SELF_HELP',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Deep Work',
    'Cal Newport',
    '9781000000087',
    'SELF_HELP',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Power of Habit',
    'Charles Duhigg',
    '9781000000088',
    'SELF_HELP',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Think and Grow Rich',
    'Napoleon Hill',
    '9781000000089',
    'SELF_HELP',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The 7 Habits of Highly Effective People',
    'Stephen R. Covey',
    '9781000000090',
    'SELF_HELP',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Rich Dad Poor Dad',
    'Robert T. Kiyosaki',
    '9781000000091',
    'SELF_HELP',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The Psychology of Money',
    'Morgan Housel',
    '9781000000092',
    'SELF_HELP',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Ikigai',
    'Héctor García and Francesc Miralles',
    '9781000000093',
    'SELF_HELP',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Can''t Hurt Me',
    'David Goggins',
    '9781000000094',
    'SELF_HELP',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Eat That Frog!',
    'Brian Tracy',
    '9781000000095',
    'SELF_HELP',
    'RESERVED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Start With Why',
    'Simon Sinek',
    '9781000000096',
    'SELF_HELP',
    'AVAILABLE'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'The One Thing',
    'Gary Keller and Jay Papasan',
    '9781000000097',
    'SELF_HELP',
    'ISSUED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Mindset',
    'Carol S. Dweck',
    '9781000000098',
    'SELF_HELP',
    'LOST'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'Essentialism',
    'Greg McKeown',
    '9781000000099',
    'SELF_HELP',
    'DAMAGED'
);

INSERT INTO books (
    id,
    title,
    author,
    isbn,
    category,
    status
)
VALUES (
    nextval('book_seq'),
    'How to Win Friends and Influence People',
    'Dale Carnegie',
    '9781000000100',
    'SELF_HELP',
    'RESERVED'
);

