package com.aman.LibraryManagementSystem.util;

import com.aman.LibraryManagementSystem.enums.BookStatus;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class BookSeedGenerator {

    public static void main(String[] args) throws IOException {

        Path csvPath = Path.of("database/books.csv");
        Path outputPath = Path.of("database/books_seed.sql");

        List<String> lines = Files.readAllLines(csvPath);
        StringBuilder sqlBuilder = new StringBuilder();

        sqlBuilder.append("""
        -- ============================================
        -- Library Management System
        -- Auto Generated Seed Data
        -- Generated by BookSeedGenerator
        -- ============================================
        """);

        for (int i = 1; i < lines.size(); i++) {

            String line = lines.get(i);

            String[] parts = line.split(",", -1);

            if (parts.length != 3) {
                throw new IllegalArgumentException(
                        "Invalid CSV format at line " + (i + 1) + ": " + line
                );
            }

            String title = parts[0].trim();
            String author = parts[1].trim();

            // Escape SQL single quotes
            title = title.replace("'", "''");
            author = author.replace("'", "''");

            String category = parts[2].trim();

            String isbn = String.format(
                    "978100000%04d",
                    i
            );

            BookStatus status =
                    BookStatus.values()[
                            (i - 1) % BookStatus.values().length
                            ];

            sqlBuilder.append("""
            INSERT INTO books (
                id,
                title,
                author,
                isbn,
                category,
                status
            )
            VALUES (
                nextval('book_seq'),
                '%s',
                '%s',
                '%s',
                '%s',
                '%s'
            );

            """.formatted(
                    title,
                    author,
                    isbn,
                    category,
                    status
            ));
        }

        Files.writeString(
                outputPath,
                sqlBuilder.toString(),
                StandardCharsets.UTF_8
        );

        System.out.println(
                "Seed file generated successfully!"
        );

        System.out.println(
                outputPath.toAbsolutePath()
        );
    }
}